# NVIDIA Linux Open GPU Kernel Modules CI
name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make modules

    - name: Test
      run: echo "No automated tests available for kernel modules"

